Testing change

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -3,6 +3,8 @@ name: Test
 on:
   pull_request:
     types: [opened, synchronize, reopened]
+  merge_group:
+    types: [checks_requested]
 
 jobs:
   test:
@@ -12,4 +14,10 @@ jobs:
         uses: actions/checkout@v4
       
       - name: Run test
-        run: echo "Test passed!" 
+        run: |
+          if [ "${{ github.event_name }}" = "pull_request" ]; then
+            echo "Failing test on pull request"
+            exit 1
+          else
+            echo "Test passed on merge queue!"
+          fi 
